"""Initial migration

Revision ID: 4641a18227dc
Revises: 
Create Date: 2025-05-23 19:38:22.121150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4641a18227dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('qr_code_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('landmark_id', sa.Integer(), nullable=False),
    sa.Column('tourist_info', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['landmark_id'], ['landmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_log')
    op.drop_table('landmark')
    # ### end Alembic commands ###
